import type { Metadata } from 'next';
import { Kanit } from 'next/font/google';
import '@/styles/globals.css';
import StyledComponentsRegistry from '@/libs/AntdRegistry';
import { ConfigProvider } from 'antd';
import theme from '@/styles/theme/themeConfig';

const kanit = Kanit({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Todo Thun</title>
        <link rel="shortcut icon" href="/public/logo.svg" />
        <meta name="author" content="Thun" />
        <meta property="og:url" content="https://todos.thun.dev" />
        <meta property="og:type" content="website" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <meta charSet="utf-8" />
      </head>
      <body className={kanit.className}>
        <StyledComponentsRegistry>
          <ConfigProvider theme={theme}>{children}</ConfigProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
